[Settings]
; =========================
; 全局功能开关
; =========================

open_update = True
open_empty_category = False
open_update_time = True
open_url_info = True
open_epg = True
open_m3u_result = True
urls_limit = 10
update_time_position = top
language = zh_CN

; =========================
; 定时执行设置
; =========================

update_mode = interval
update_interval = 6
update_startup = True
time_zone = Asia/Shanghai

; =========================
; 文件路径设置
; =========================

source_file = config/demo.txt
final_file = output/result.txt
open_realtime_write = True

; =========================
; 页面服务设置
; =========================

open_service = True
app_port = 5180
public_scheme = https

; =========================
; 数据源设置
; =========================

open_local = True
open_subscribe = True
open_history = True
subscribe_urls = https://raw.githubusercontent.com/iptv-org/iptv/master/streams/cn.m3u,https://raw.githubusercontent.com/iptv-org/iptv/master/streams/hk.m3u,https://raw.githubusercontent.com/iptv-org/iptv/master/streams/tw.m3u,https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u,https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u
open_headers = False

; =========================
; 测速与筛选设置
; =========================

open_speed_test = True
open_filter_resolution = True
open_filter_speed = True
open_filter_delay = True

min_speed = 0.2
min_resolution = 720p
max_delay = 8000

open_ipv6 = True
open_ipv4 = True

; =========================
; 结果排序设置
; =========================

sort_mode = speed
